import {
  BillTC,
  BrandTC,
  CategoryTC,
  ClientTC,
  CreditTC,
  CreditNoteTC,
  CurrencyTC,
  DeliveryNoteTC,
  LocationTC,
  ModelTC,
  OrderTC,
  OrderProductTC,
  ProductTC,
  PromoCodeTC,
  SettingTC,
  ShippingTC,
  ShopCartTC,
  SupplierTC,
  UserTC,
  VariantTC,
  VariantValueTC,
} from '../models';

const Mutation = {
  // Bills
  // createBill: BillTC.mongooseResolvers.createOne(),
  // createManyBills: BillTC.mongooseResolvers.createMany(),
  updateBillById: BillTC.mongooseResolvers.updateById(),
  updateBill: BillTC.mongooseResolvers.updateOne(),
  updateBills: BillTC.mongooseResolvers.updateMany(),
  deleteBillById: BillTC.mongooseResolvers.removeById(),
  deleteBill: BillTC.mongooseResolvers.removeOne(),
  deleteBills: BillTC.mongooseResolvers.removeMany(),
  // Brand
  createBrand: BrandTC.mongooseResolvers.createOne(),
  createManyBrands: BrandTC.mongooseResolvers.createMany(),
  updateBrandById: BrandTC.mongooseResolvers.updateById(),
  updateBrand: BrandTC.mongooseResolvers.updateOne(),
  updateBrands: BrandTC.mongooseResolvers.updateMany(),
  deleteBrandById: BrandTC.mongooseResolvers.removeById(),
  deleteBrand: BrandTC.mongooseResolvers.removeOne(),
  deleteBrands: BrandTC.mongooseResolvers.removeMany(),
  // Category
  createCategory: CategoryTC.mongooseResolvers.createOne(),
  createManyCategories: CategoryTC.mongooseResolvers.createMany(),
  updateCategoryById: CategoryTC.mongooseResolvers.updateById(),
  updateCategory: CategoryTC.mongooseResolvers.updateOne(),
  updateCategories: CategoryTC.mongooseResolvers.updateMany(),
  deleteCategoryById: CategoryTC.mongooseResolvers.removeById(),
  deleteCategory: CategoryTC.mongooseResolvers.removeOne(),
  deleteCategories: CategoryTC.mongooseResolvers.removeMany(),
  // Client
  createClient: ClientTC.mongooseResolvers.createOne(),
  createManyClients: ClientTC.mongooseResolvers.createMany(),
  updateClientById: ClientTC.mongooseResolvers.updateById(),
  updateClient: ClientTC.mongooseResolvers.updateOne(),
  updateClients: ClientTC.mongooseResolvers.updateMany(),
  deleteClientById: ClientTC.mongooseResolvers.removeById(),
  deleteClient: ClientTC.mongooseResolvers.removeOne(),
  deleteClients: ClientTC.mongooseResolvers.removeMany(),
  // Credit
  createCredit: CreditTC.mongooseResolvers.createOne(),
  createManyCredits: CreditTC.mongooseResolvers.createMany(),
  updateCreditById: CreditTC.mongooseResolvers.updateById(),
  updateCredit: CreditTC.mongooseResolvers.updateOne(),
  updateCredits: CreditTC.mongooseResolvers.updateMany(),
  deleteCreditById: CreditTC.mongooseResolvers.removeById(),
  deleteCredit: CreditTC.mongooseResolvers.removeOne(),
  deleteCredits: CreditTC.mongooseResolvers.removeMany(),
  // CreditNote
  createCreditNote: CreditNoteTC.mongooseResolvers.createOne(),
  createManyCreditNotes: CreditNoteTC.mongooseResolvers.createMany(),
  updateCreditNoteById: CreditNoteTC.mongooseResolvers.updateById(),
  updateCreditNote: CreditNoteTC.mongooseResolvers.updateOne(),
  updateCreditNotes: CreditNoteTC.mongooseResolvers.updateMany(),
  deleteCreditNoteById: CreditNoteTC.mongooseResolvers.removeById(),
  deleteCreditNote: CreditNoteTC.mongooseResolvers.removeOne(),
  deleteCreditNotes: CreditNoteTC.mongooseResolvers.removeMany(),
  // Currency
  createCurrency: CurrencyTC.mongooseResolvers.createOne(),
  createManyCurrency: CurrencyTC.mongooseResolvers.createMany(),
  updateCurrencyById: CurrencyTC.mongooseResolvers.updateById(),
  updateCurrency: CurrencyTC.mongooseResolvers.updateOne(),
  updateCurrencies: CurrencyTC.mongooseResolvers.updateMany(),
  deleteCurrencyById: CurrencyTC.mongooseResolvers.removeById(),
  deleteCurrency: CurrencyTC.mongooseResolvers.removeOne(),
  deleteCurrencies: CurrencyTC.mongooseResolvers.removeMany(),
  // DeliveryNote
  createDeliveryNote: DeliveryNoteTC.mongooseResolvers.createOne(),
  createManyDeliveryNote: DeliveryNoteTC.mongooseResolvers.createMany(),
  updateDeliveryNoteById: DeliveryNoteTC.mongooseResolvers.updateById(),
  updateDeliveryNote: DeliveryNoteTC.mongooseResolvers.updateOne(),
  updateDeliveryNotes: DeliveryNoteTC.mongooseResolvers.updateMany(),
  deleteDeliveryNoteById: DeliveryNoteTC.mongooseResolvers.removeById(),
  deleteDeliveryNote: DeliveryNoteTC.mongooseResolvers.removeOne(),
  deleteDeliveryNotes: DeliveryNoteTC.mongooseResolvers.removeMany(),
  // Location
  createLocation: LocationTC.mongooseResolvers.createOne(),
  createManyLocation: LocationTC.mongooseResolvers.createMany(),
  updateLocationById: LocationTC.mongooseResolvers.updateById(),
  updateLocation: LocationTC.mongooseResolvers.updateOne(),
  updateLocations: LocationTC.mongooseResolvers.updateMany(),
  deleteLocationById: LocationTC.mongooseResolvers.removeById(),
  deleteLocation: LocationTC.mongooseResolvers.removeOne(),
  deleteLocations: LocationTC.mongooseResolvers.removeMany(),
  // Model
  createModel: ModelTC.mongooseResolvers.createOne(),
  createManyModel: ModelTC.mongooseResolvers.createMany(),
  updateModelById: ModelTC.mongooseResolvers.updateById(),
  updateModel: ModelTC.mongooseResolvers.updateOne(),
  updateModels: ModelTC.mongooseResolvers.updateMany(),
  deleteModelById: ModelTC.mongooseResolvers.removeById(),
  deleteModel: ModelTC.mongooseResolvers.removeOne(),
  deleteModels: ModelTC.mongooseResolvers.removeMany(),
  // Order
  // createOrder: OrderTC.mongooseResolvers.createOne(),
  // createManyOrder: OrderTC.mongooseResolvers.createMany(),
  // updateOrderById: OrderTC.mongooseResolvers.updateById(),
  // updateOrder: OrderTC.mongooseResolvers.updateOne(),
  // updateOrders: OrderTC.mongooseResolvers.updateMany(),
  deleteOrderById: OrderTC.mongooseResolvers.removeById(),
  deleteOrder: OrderTC.mongooseResolvers.removeOne(),
  deleteOrders: OrderTC.mongooseResolvers.removeMany(),
  // OrderProduct
  createOrderProduct: OrderProductTC.mongooseResolvers.createOne(),
  createManyOrderProduct: OrderProductTC.mongooseResolvers.createMany(),
  updateOrderProductById: OrderProductTC.mongooseResolvers.updateById(),
  updateOrderProduct: OrderProductTC.mongooseResolvers.updateOne(),
  updateOrderProducts: OrderProductTC.mongooseResolvers.updateMany(),
  deleteOrderProductById: OrderProductTC.mongooseResolvers.removeById(),
  deleteOrderProduct: OrderProductTC.mongooseResolvers.removeOne(),
  deleteOrderProducts: OrderProductTC.mongooseResolvers.removeMany(),
  // Products
  // createProduct: ProductTC.mongooseResolvers.createOne(),
  // createManyProducts: ProductTC.mongooseResolvers.createMany(),
  // updateProductById: ProductTC.mongooseResolvers.updateById(),
  // updateProduct: ProductTC.mongooseResolvers.updateOne(),
  // updateProducts: ProductTC.mongooseResolvers.updateMany(),
  deleteProductById: ProductTC.mongooseResolvers.removeById(),
  deleteProduct: ProductTC.mongooseResolvers.removeOne(),
  deleteProducts: ProductTC.mongooseResolvers.removeMany(),
  // PromoCode
  createPromoCode: PromoCodeTC.mongooseResolvers.createOne(),
  createManyPromoCode: PromoCodeTC.mongooseResolvers.createMany(),
  updatePromoCodeById: PromoCodeTC.mongooseResolvers.updateById(),
  updatePromoCode: PromoCodeTC.mongooseResolvers.updateOne(),
  updatePromoCodes: PromoCodeTC.mongooseResolvers.updateMany(),
  deletePromoCodeById: PromoCodeTC.mongooseResolvers.removeById(),
  deletePromoCode: PromoCodeTC.mongooseResolvers.removeOne(),
  deletePromoCodes: PromoCodeTC.mongooseResolvers.removeMany(),
  // Settings
  // createSetting: SettingTC.mongooseResolvers.createOne(),
  // createManySetting: SettingTC.mongooseResolvers.createMany(),
  // updateSettingById: SettingTC.mongooseResolvers.updateById(),
  // updateSetting: SettingTC.mongooseResolvers.updateOne(),
  // updateSettings: SettingTC.mongooseResolvers.updateMany(),
  // deleteSettingById: SettingTC.mongooseResolvers.removeById(),
  // deleteSetting: SettingTC.mongooseResolvers.removeOne(),
  // deleteSettings: SettingTC.mongooseResolvers.removeMany(),
  // Shipping
  createShipping: ShippingTC.mongooseResolvers.createOne(),
  createManyShipping: ShippingTC.mongooseResolvers.createMany(),
  updateShippingById: ShippingTC.mongooseResolvers.updateById(),
  updateShipping: ShippingTC.mongooseResolvers.updateOne(),
  updateShippings: ShippingTC.mongooseResolvers.updateMany(),
  deleteShippingById: ShippingTC.mongooseResolvers.removeById(),
  deleteShipping: ShippingTC.mongooseResolvers.removeOne(),
  deleteShippings: ShippingTC.mongooseResolvers.removeMany(),
  // ShopCart
  createShopCart: ShopCartTC.mongooseResolvers.createOne(),
  createManyShopCart: ShopCartTC.mongooseResolvers.createMany(),
  updateShopCartById: ShopCartTC.mongooseResolvers.updateById(),
  updateShopCart: ShopCartTC.mongooseResolvers.updateOne(),
  updateShopCarts: ShopCartTC.mongooseResolvers.updateMany(),
  deleteShopCartById: ShopCartTC.mongooseResolvers.removeById(),
  deleteShopCart: ShopCartTC.mongooseResolvers.removeOne(),
  deleteShopCarts: ShopCartTC.mongooseResolvers.removeMany(),
  // Supplier
  createSupplier: SupplierTC.mongooseResolvers.createOne(),
  createManySupplier: SupplierTC.mongooseResolvers.createMany(),
  updateSupplierById: SupplierTC.mongooseResolvers.updateById(),
  updateSupplier: SupplierTC.mongooseResolvers.updateOne(),
  updateSuppliers: SupplierTC.mongooseResolvers.updateMany(),
  deleteSupplierById: SupplierTC.mongooseResolvers.removeById(),
  deleteSupplier: SupplierTC.mongooseResolvers.removeOne(),
  deleteSuppliers: SupplierTC.mongooseResolvers.removeMany(),
  // Users
  createUser: UserTC.mongooseResolvers.createOne(),
  createManyUsers: UserTC.mongooseResolvers.createMany(),
  updateUserById: UserTC.mongooseResolvers.updateById(),
  updateUser: UserTC.mongooseResolvers.updateOne(),
  updateUsers: UserTC.mongooseResolvers.updateMany(),
  deleteUserById: UserTC.mongooseResolvers.removeById(),
  deleteUser: UserTC.mongooseResolvers.removeOne(),
  deleteUsers: UserTC.mongooseResolvers.removeMany(),
  // Variant
  createVariant: VariantTC.mongooseResolvers.createOne(),
  createManyVariants: VariantTC.mongooseResolvers.createMany(),
  updateVariantById: VariantTC.mongooseResolvers.updateById(),
  updateVariant: VariantTC.mongooseResolvers.updateOne(),
  updateVariants: VariantTC.mongooseResolvers.updateMany(),
  deleteVariantById: VariantTC.mongooseResolvers.removeById(),
  deleteVariant: VariantTC.mongooseResolvers.removeOne(),
  deleteVariants: VariantTC.mongooseResolvers.removeMany(),
  // VariantValue
  createVariantValue: VariantValueTC.mongooseResolvers.createOne(),
  createManyVariantValues: VariantValueTC.mongooseResolvers.createMany(),
  updateVariantValueById: VariantValueTC.mongooseResolvers.updateById(),
  updateVariantValue: VariantValueTC.mongooseResolvers.updateOne(),
  updateVariantValues: VariantValueTC.mongooseResolvers.updateMany(),
  deleteVariantValueById: VariantValueTC.mongooseResolvers.removeById(),
  deleteVariantValue: VariantValueTC.mongooseResolvers.removeOne(),
  deleteVariantValues: VariantValueTC.mongooseResolvers.removeMany(),
};

export default Mutation;
